input {
  # For JSON files, in the ingest_data directory
  file {
    mode => "tail"
    path => "/usr/share/logstash/ingest_data/*.json"
    codec => "json" 
    start_position => "beginning"
    type => "data_ingest"
  }
  file {
    path => "/usr/share/logstash/backend_logs/*.log"
    codec => "json"
    start_position => "beginning"
    type => "backend_log"
  }
}

filter { 
  if [type] == "data_ingest" {
    mutate {
      rename => { "[_id][$$oid]" => "mongo_id" }
      lowercase => [ "cuerpo" ]
    }
  }

  if [type] == "backend_log" {
    if [level] == "http" {
      grok {
        match => { "message" => "%{IPORHOST:clientip} %{USER:ident} %{USER:auth} \[%{HTTPDATE:morgan_timestamp}\] \"%{WORD:verb} %{DATA:request} HTTP/%{NUMBER:httpversion}\" %{NUMBER:response:int} %{NUMBER:bytes:int} %{QS:referrer} %{QS:agent} - %{NUMBER:response_time:float} ms" }
      }
    }
  }
}

output {
  if [type] == "data_ingest" {
    elasticsearch {
      hosts => "${ELASTIC_HOSTS}"
      user => "${ELASTIC_USER}"
      password => "${ELASTIC_PASSWORD}"
      cacert => "/usr/share/logstash/certs/ca/ca.crt"
      index => "docs_oposearch"
      document_id => "%{mongo_id}" 
    }
  } else if [type] == "backend_log" {
    elasticsearch {
      hosts => "${ELASTIC_HOSTS}"
      user => "${ELASTIC_USER}"
      password => "${ELASTIC_PASSWORD}"
      cacert => "/usr/share/logstash/certs/ca/ca.crt"
      index => "oposearch-logs-%{+YYYY.MM.dd}"
    }
  }
  
  stdout { codec => rubydebug }
}