input {
  # For JSON files, in the ingest_data directory
  file {
    mode => "tail"
    path => "/usr/share/logstash/ingest_data/*.json"
    codec => "json" 
    start_position => "beginning"
  }
  file {
    path => "/usr/share/logstash/ingest_data/logs/*.log"
    codec => "json"
    type => "backend-logs"
  }
}



filter { 
  mutate {
    rename => { "[_id][$$oid]" => "mongo_id" }
    lowercase => [ "cuerpo" ]
  }
}

output {
  elasticsearch {
    hosts => "${ELASTIC_HOST}"
    user => "${ELASTIC_USER}"
    password => "${ELASTIC_PASSWORD}"
    
    cacert => "/usr/share/logstash/certs/ca/ca.crt"
    
    index => "docs_oposearch"
    
    document_id => "%{mongo_id}" 
  }
  
  stdout { codec => rubydebug }
}